name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
    steps:
      - name: Create release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Ragon.SimpleServer-${{ github.ref }}
          prerelease: false

  build:
    name: Release
    needs: release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Get Tag
      shell: bash
      run: |
        echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
 
    - name: Build
      shell: bash
      run: |
          release_name="Runlang.App-${{ env.TAG }}"
          
          npm install -g @vue/cli
          npm install
          
          # Build everything
          npm run build
          
          # Pack files        
          7z a -tzip "${release_name}.zip" "./dist/*"
  
          # Delete output directory
          rm -r "dist"
          
    - name: Upload
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: Runlang.App-${{ env.TAG }}.zip
        asset_name: Runlang.App-${{ env.TAG }}.zip
        asset_content_type: application/zip
